model :
  type : 'ConvTasNet'
  n_fft : 512
  d_feature : 256
  l_filter_f : 1 # 0 : cRM, > 0 : cRF
  l_filter_t : 1  # 0 : cRM, > 0 : cRF
  activation : 'Softplus' # Sigmoid, Softplus, Tanh
  n_target : 4
  TCN_activation : "None" # None, Tanh, Sigmoid, PReLU
  phase : "cossinIPD"
  mono : false
  LPS : false
  phase_full : true
  only_azim : true
  ADPIT : true
  azim_shaking : 0
  Softplus:
    threshold : 20 #default 20
  c_out : 4
  separator : "TCN"
  output_type : "mask"
---
train:
  epoch: 25 # about 3-day in RTX 3090
  batch_size: 32
  num_workers: 16
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  summary_interval: 10
  validation_interval: 100
  checkpoint_interval: 1000
---
loss:
  type: 'wSDRLoss' # mSDRLoss,wSDRLoss,iSDRLoss
  cross : false
  wSDRLoss : 
    alpha : 0.1  
  wMSELoss : 
    alpha : 0.1
---
scheduler: # Plateau, oneCycle, None
  type: 'Plateau'
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
---
data:
  root_train : '/home/data2/kbh/LGE/DESED_5000'
  root_test  : '/home/data2/kbh/LGE/DESED_5000'
  n_frame : 125
  n_channel : 4
  preemphasis : true
  preemphasis_coef : 0.97
  preemphasis_order : 3
  ADPIT : true
  preprocessed : true
---
  log:
    root : '/home/nas/user/kbh/DOA-Audio-Separation/'
    sample : ''