model:
  type : "DSS_v1"
  input : ["mag","cosIPD","AF"]
---
train:
  epoch: 50
  batch_size: 32
  num_workers: 32
  optimizer: 'adam'
  adam: 0.0001
  adabound:
    initial: 0.001
    final: 0.05
  frame_num: 128
  summary_interval: 10
  validation_interval: 100
  checkpoint_interval: 1000
---
loss:
  type: 'wSDRLoss'
  wSDRLoss :
    alpha : 0.99
---
scheduler: # Plateau, oneCycle, CosineAnnealingLR
  type: 'Plateau'
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
  CosineAnnealingLR : 
    T_max : 100  # Maximum number of iterations.
    eta_min : 0.000001
---
data:
  train : "/home/data2/kbh/DOA/v0/train/"
  test : "/home/data2/kbh/DOA/v0/test/"
---
log:
  root : '/home/nas/user/kbh/DSS'
  plot_spec : True
  plot_audio : True
---
audio:
  n_fft : 512
  n_hop : 128
  sr : 16000
  n_channel : 4