model :
  type : 'ResUNet'
---
loss:
  type: 'Loss_mag_wav' 
---
train:
  epoch: 30
  batch_size: 16
---
data:
  root_train : '/home/data2/kbh/LGE/v9_AIO_test'
  root_test  : '/home/data2/kbh/LGE/v9_AIO_test'